### ISSUE TITLE
Unity 2019.3 new UI folder fix

### ISSUE THREAD

**Issue by reinholdsberzins** [Placeholder-Software/FancyFolders#2]
Since the 2019.3 there is a new UI to the whole Unity engine. And the FancyFolders shows up inside the new folder icon not replace it. Here is a screenshot:
![image](https://user-images.githubusercontent.com/24436198/71777514-bb811980-2fa9-11ea-9e12-4b6af833e50d.png)
The issue is not persisten on the left side:
![image](https://user-images.githubusercontent.com/24436198/71777519-c63bae80-2fa9-11ea-8032-42790b27454b.png)

**Comment by martindevans** [comment]
Oops, that doesn't look good. I'll look into putting together a new set of default assets for `2019.3` and above.

**Comment by EP-Toushirou** [comment]
hello, does this fix? I want to buy this asset too, but this really doesn't look good.  Thanks. @martindevans

**Comment by martindevans** [comment]
Hi @EP-Toushirou I've just finished putting together a prototype for Unity 2019.4 support. We'll be releasing it onto the asset store very soon (within a couple of weeks). If you purchase before then feel free to email me (martin@placeholder-software.co.uk) your invoice number and I'll be happy to send you back a preview of the new version.
