### ISSUE TITLE
Error in UNITY Editor

### ISSUE THREAD

**Issue by subkiller974** [Placeholder-Software/FancyFolders#5]
Unable to parse file Assets/Plugins/FancyFolders/Fancy Folders Settings.asset: [Parser Failure at line 43434: Expect ':' between key and value within mapping]
Unable to parse file Assets/Plugins/FancyFolders/Fancy Folders Settings.asset: [Parser Failure at line 57318: Expect ':' between key and value within mapping]
and similars to others lines

**Comment by subkiller974** [comment]
<img width="524" alt="TMP Error Fancy" src="https://user-images.githubusercontent.com/2084951/102703969-381e0e00-4276-11eb-9537-180d7f5beeec.PNG">

**Comment by martindevans** [comment]
This is sometimes caused by an import error in Unity. Restarting the editor or reimporting assets can often fix it: https://forum.unity.com/threads/unable-to-parse-file-assets-fonts-fontname-asset-solved.538720/
